---
repository:
  # See https://github.com/apps/settings for all available settings.

  # The name of the repository. Changing this will rename the repository
  name: cloud-rooster

  topics: aws, cloudformation, python

  # A short description of the repository that will show up on GitHub
  description: The cloud roster for keeping track of your flock of roosters

  # Either `true` to make the repository private, or `false` to make it public.
  private: false

  # Updates the default branch for this repository.
  default_branch: main

  # Either `true` to allow squash-merging pull requests, or `false` to prevent
  # squash-merging.
  allow_squash_merge: true

  # Either `true` to allow merging pull requests with a merge commit, or `false`
  # to prevent merging pull requests with merge commits.
  allow_merge_commit: true

  # Either `true` to allow rebase-merging pull requests, or `false` to prevent
  # rebase-merging.
  allow_rebase_merge: true

  # Disable issues
  has_issues: true

  # Disable wiki
  has_wiki: true

  homepage: https://github.com/FlatTire/cloud-rooster

# Specify what collaborators have what permissions
collaborators: []

# Define labels and colors
labels:
  - name: api
    color: D62BD0
  - name: batch
    color: 2BBDBA
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  - name: unit-test
    color: 733EC2

branches:
  - name: main
    # https://developer.github.com/v3/repos/branches/#update-branch-protection
    # Branch Protection settings. Set to null to disable
    protection:
      # Required. Require at least one approving review on a pull request, before merging. Set to null to disable.
      required_pull_request_reviews:
        # The number of approvals required. (1-6)
        required_approving_review_count: 1
        # Dismiss approved reviews automatically when a new commit is pushed.
        dismiss_stale_reviews: true
        # Blocks merge until code owners have reviewed.
        require_code_owner_reviews: false
        # Specify which users and teams can dismiss pull request reviews. Pass an empty dismissal_restrictions object to disable. User and team dismissal_restrictions are only available for organization-owned repositories. Omit this parameter for personal repositories.
        dismissal_restrictions: {}
      # Required. Require status checks to pass before merging. Set to null to disable
      required_status_checks:
        # Required. Require branches to be up to date before merging.
        strict: true
        # Required. The list of status checks to require in order to merge into this branch
        contexts: []
      # Required. Enforce all configured restrictions for administrators. Set to true to enforce required status checks for repository administrators. Set to null to disable.
      enforce_admins: true
      # Required. Restrict who can push to this branch. Team and user restrictions are only available for organization-owned repositories. Set to null to disable.
      restrictions:
        users: []
        teams: []

# vim: ft=yaml sw=2 ts=2
